equipment_profile:

  access_control: true
  firewall: true

  console: console=tty0 console=ttyS0,115200n8
  kernel_parameters:

  operating_system:
    distribution: centos
    distribution_major_version: 8
    distribution_version: 8.1

  equipment_type: server

  configuration:
    keyboard_layout: us
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: x86_64

